name: DevTools
main: DevTools\DevTools
version: 1.10.2
api: 1.3.1
load: STARTUP
author: PocketMine Team
description: Helps develop and distribute PocketMine-MP plugins
website: https://github.com/IceCruelStuff/DevTools
